logging:
  level:
    org:
      hibernate:
        SQL: debug
server:
  port: ${PORT:8080}
spring:
  datasource:
    url: jdbc:mysql://localhost/db_inventory_sp3?useTimezone=true&serverTimezone=America/El_Salvador&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: orion1993$
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # Por defecto ya sabe que dialecto se debe usar por su datasource
    # database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5978
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days